=== niranjanthapa6441/XML-SongSTore/catalog_19031196.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Store">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="storesInformation" minOccurs="0" maxOccurs="1" />
                <xs:element ref="songs" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="storesInformation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="logo"></xs:element>
                <xs:element ref="storeName" />
                <xs:element ref="phoneNumber" />
                <xs:element ref="address" />
                <xs:element ref="website" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="songs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="song" minOccurs="1" maxOccurs="18" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="song">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="image"></xs:element>
                <xs:element ref="title" />
                <xs:element ref="genre" />
                <xs:element ref="album" />
                <xs:element ref="singers" minOccurs="0" maxOccurs="1" />
                <xs:element ref="band" minOccurs="0" maxOccurs="1" />
                <xs:element ref="musicDirectors" minOccurs="0" maxOccurs="1" />
                <xs:element ref="producers" minOccurs="0" maxOccurs="1" />
                <xs:element ref="writers" minOccurs="0" maxOccurs="1" />
                <xs:element ref="productionHouse" minOccurs="0" maxOccurs="1" />
                <xs:element ref="length" />
                <xs:element ref="recorded" />
                <xs:element ref="released" />
            </xs:sequence>
            <xs:attribute name="songID" use="required" type="xs:integer" />
        </xs:complexType>
    </xs:element>
    <xs:element name="singers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="sangBy" minOccurs="1" maxOccurs="4" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="musicDirectors">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="directedBy" minOccurs="1" maxOccurs="3" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="producers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="producedBy" minOccurs="1" maxOccurs="4" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="writers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="writtenBy" minOccurs="1" maxOccurs="3" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="genre">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tag" />
                <xs:element ref="genrename" />
            </xs:sequence>
            <xs:attribute name="genreID" use="optional" type="validate"></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="validate">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Jazz"></xs:enumeration>
            <xs:enumeration value="HipHop"></xs:enumeration>
            <xs:enumeration value="Rock"></xs:enumeration>
            <xs:enumeration value="Dubstep"></xs:enumeration>
            <xs:enumeration value="Country"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="storeName">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[A-Z]([a-z])+ [A-Z]([a-z])+ [A-Z]([a-z])+" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="phoneNumber">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tag"></xs:element>
                <xs:element name="countryCode" type="xs:string"/>
                <xs:element ref="number"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="number">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="\d{10}"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="productionHouse">
        <xs:simpleType>
            <xs:restriction base="xs:string"></xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="tag">
        <xs:simpleType>
            <xs:restriction base="xs:string"></xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="genrename">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="HipHop" />
                <xs:enumeration value="Jazz" />
                <xs:enumeration value="Rock" />
                <xs:enumeration value="Dubstep" />
                <xs:enumeration value="Country" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="address">
        <xs:simpleType>
            <xs:restriction base="xs:string"></xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="website">
        <xs:simpleType>
            <xs:restriction base="xs:string"></xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="title">
        <xs:simpleType>
            <xs:restriction base="xs:string"></xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="length">
        <xs:simpleType>
            <xs:restriction base="xs:string"></xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="recorded">
        <xs:simpleType>
            <xs:restriction base="xs:string"></xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="released">
        <xs:simpleType>
            <xs:restriction base="xs:string"></xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="image">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="imgid" use="required" type="xs:integer"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="band">
        <xs:simpleType>
            <xs:restriction base="xs:string"></xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="sangBy">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="singerID" use="required" type="xs:string" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="directedBy">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="musicDirectorID" use="required" type="xs:string" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="writtenBy">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="writerID" use="required" type="xs:string" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="producedBy">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="producerID" use="required" type="xs:string" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="album">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="albumID" use="optional" type="xs:ID" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== niranjanthapa6441/XML-SongSTore/catalog_19031196_schemaValidarion.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="final.css" type="text/css"?>
<Store  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_19031196.xsd">
    <storesInformation>
        <logo logoId="1"></logo>
        <storeName>Nepal Music Academy</storeName>
        <phoneNumber>
            <tag>| Phone No:</tag>
            <countryCode>+977</countryCode> 
            <number>9810314782</number>
        </phoneNumber>
        <address> | Address: JP Marga,Thamel,Kathmandu,Nepal</address>
        <website>| Website: nepalmusicacademy.com.np |</website>
    </storesInformation>
    <songs>
        <song songID="1">
            <image imgid="1"></image>
            <title>Rap God</title>
                <genre genreID="HipHop">
                    <tag>Genre:</tag>
                    <genrename>HipHop</genrename>
                </genre>
                <album albumID="sad">Album: The Marshall Mathers LP 2</album>
                <singers>
                    <sangBy singerID="1">Artist: Eminem</sangBy>
                </singers>
                <musicDirectors>
                    <directedBy musicDirectorID="1">Directed By: AfterMath</directedBy>
                </musicDirectors>
                <producers>
                    <producedBy producerID="1">Producer: DVLP</producedBy>
                    <producedBy producerID="2">Filthy(co)</producedBy>
                </producers>
                <writers>
                    <writtenBy writerID="1">Written By: Eminem</writtenBy>
                    <writtenBy writerID="2">Sick Rick</writtenBy>
                </writers>
                <length>length: 6:04</length>
                <recorded>Recorded: 2012</recorded>
                <released>Released: 2013</released>
        </song>
        <song songID="2">
            <image imgid="2"></image>
            <title>Here Comes the Sun</title>
                <genre genreID="Rock">
                    <tag>Genre:</tag>
                    <genrename>Rock</genrename>
                </genre>
                <album albumID="sa">Album: Abbey Road </album>
                <band>Band:The Beatles</band>
                <musicDirectors>
                    <directedBy musicDirectorID="1">Directed By:Eric Clapton </directedBy>
                </musicDirectors>
                <producers>
                    <producedBy producerID="1">Producer:George Martin </producedBy>
                </producers>
                <writers>
                    <writtenBy writerID="1">Written By: George Harrisson</writtenBy>
                </writers>
                <productionHouse>Production House: Apple</productionHouse>
                <length>length: 3:06</length>
                <recorded>Recorded: 7th july-19th August 1969</recorded>
                <released>Released: 26 September 1969</released>

        </song>
        <song songID="15">
            <image imgid="15"></image>
            <title>Can't Stop the Feeling</title>
                <genre genreID="HipHop">
                    <tag>Genre:</tag>
                    <genrename>HipHop</genrename>
                </genre>
                <album albumID="B15">Album: Trolls: Original Motion Picture Soundtrack</album>
                <singers>
                    <sangBy singerID="1">Artist: Justin Timberlake</sangBy>
                </singers>
                <musicDirectors>
                    <directedBy musicDirectorID="1">Directed By: Mark Romanek</directedBy>
                </musicDirectors>
                <producers>
                    <producedBy producerID="1">Producer:Max Martin,
                </producedBy>
                    <producedBy producerID="2">Justin Timberlake</producedBy>
                </producers>
                <writers>
                    <writtenBy writerID="1">Written By:Johan Schuster,</writtenBy>
                    <writtenBy writerID="2">Max Martin</writtenBy>
                    <writtenBy writerID="3">Justin Timberlake</writtenBy>
                </writers>
                <productionHouse>Production House: RCA</productionHouse>
                <length>length: 3:52</length>
                <recorded>Recorded: 2016</recorded>
                <released>Released: 6 May,2016</released>
        </song>
        <song songID="16">
            <image imgid="16"></image>
            <title>Godzilla</title>
                <genre genreID="HipHop">
                    <tag>Genre:</tag>
                    <genrename>HipHop</genrename>
                </genre>
                <album albumID="B13">Album: Music To Be Murdered By</album>
                <singers>
                    <sangBy singerID="1">Artist: Eminem</sangBy>
                </singers>
                <musicDirectors>
                    <directedBy musicDirectorID="1">Directed By: Cole Bennett</directedBy>
                </musicDirectors>
                <producers>
                    <producedBy producerID="1">Producer: Eminem,
                </producedBy>
                    <producedBy producerID="2">D.A. Doman</producedBy>
                </producers>
                <writers>
                    <writtenBy writerID="1">Written By:Marshall Mathers,</writtenBy>
                    <writtenBy writerID="2">Jarad Higgins,</writtenBy>
                    <writtenBy writerID="3"> David Doman</writtenBy>
                </writers>
                <productionHouse>Production House: Aftermath</productionHouse>
                <length>length: 3:30</length>
                <recorded>Recorded: 2019</recorded>
                <released>Released: 28 January,2020</released>
        </song>
        <song songID="3">
            <image imgid="3"></image>
            <title>24k Magic</title>
                <genre genreID="HipHop">
                    <tag>Genre:</tag>
                    <genrename>HipHop</genrename>
                </genre>
                <album albumID="asd">Album: 24k magic</album>
                <singers>
                    <sangBy singerID="1">Artist: Bruno Mars</sangBy>
                </singers>
                <musicDirectors>
                    <directedBy musicDirectorID="1">Directed By: Roger Trautman</directedBy>
                </musicDirectors>
                <producers>
                    <producedBy producerID="1">
                        <![CDATA[ Producer: Shampoo Press & Curl,]]>
                    </producedBy>
                    <producedBy producerID="2">The Stereotypes</producedBy>
                </producers>
                <writers>
                    <writtenBy writerID="1">Written By: Bruno Mars,</writtenBy>
                    <writtenBy writerID="2">Phillip lawrence,</writtenBy>
                    <writtenBy writerID="3">Christopher Brody Brown</writtenBy>
                </writers>
                <productionHouse>Production House: Atlantic</productionHouse>
                <length>length: 3:06</length>
                <recorded>Recorded: 2015-2016</recorded>
                <released>Released: 7 October 2016</released>
        </song>
        <song songID="4">
            <image imgid="4"></image>
            <title>Just The Way You Are</title>
                <genre genreID="HipHop">
                    <tag>Genre:</tag>
                    <genrename>HipHop</genrename>
                </genre>
                <album albumID="B2">
                    <![CDATA[Album:Doo-Wops & Hooligans ]]>
                </album>
                <singers>
                    <sangBy singerID="1">Artist: Bruno Mars</sangBy>
                </singers>
                <musicDirectors>
                    <directedBy musicDirectorID="1">Directed By:  Stephen Marcussen</directedBy>
                </musicDirectors>
                <producers>
                    <producedBy producerID="1">Producer:The Smeezingtons,
                    </producedBy>
                    <producedBy producerID="2">Needlz</producedBy>
                </producers>
                <writers>
                    <writtenBy writerID="1">Written By: Bruno Mars,</writtenBy>
                    <writtenBy writerID="2">Khari Cain,</writtenBy>
                    <writtenBy writerID="3">Khalll Walton</writtenBy>
                </writers>
                <productionHouse>Production House: ELektra, Atlantic</productionHouse>
                <length>length: 03:41 </length>
                <recorded>Recorded: 2010</recorded>
                <released>Released:	July 20, 2010 </released>
        </song>
        <song songID="5">
            <image imgid="5"></image>
            <title>Take Me Home</title>
                <genre genreID="Country">
                    <tag>Genre:</tag>
                    <genrename>Country</genrename>
                </genre>
                <album albumID="B3">
                    Album:
                    <![CDATA[Poems, Prayers & Promise]]>
                </album>
                <singers>
                    <sangBy singerID="1">Artist: John Denver</sangBy>
                </singers>
                <musicDirectors>
                    <directedBy musicDirectorID="1">Directed By:Jay Rockefeller </directedBy>
                </musicDirectors>
                <producers>
                    <producedBy producerID="1">Producer: Milton OKun,
                    </producedBy>
                    <producedBy producerID="2">Susan Ruskin</producedBy>
                </producers>
                <writers>
                    <writtenBy writerID="1">Written By:Bill Danoff,</writtenBy>
                    <writtenBy writerID="2">Taffy Nivert,</writtenBy>
                    <writtenBy writerID="3">John Denver</writtenBy>
                </writers>
                <productionHouse>Production House: RCA</productionHouse>
                <length>length: 3:17</length>
                <recorded>Recorded: January 1971 </recorded>
                <released>Released: April 12, 1971</released>
        </song>
